apiVersion: v1
kind: ConfigMap
metadata:
  name: bets-config
data:
 MATCH_SVC: "http://matches:9999/api/matches/<ID>"
 CHAMPIONSHIP_SVC: "http://championships:9999/api/championships/<ID>"
 PLAYER_SVC: "http://players:9999/api/players/<ID>"
